language: node_js
node_js:
  - 14 # use nodejs v14 LTS
os: linux
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master # build master branch only
script:
  - yarn build
deploy:
  provider: pages
  token: $GH_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  local_dir: docs
